#!/bin/python3

ARRAY_NAMES = ["VERTEX_SRC", "FRAGMENT_SRC"]
FILE_NAMES = ["vertex.glsl", "fragment.glsl"]

output = open("../src/core/shadersrc.h", "w")
output.write("// Generated by a script, see 'shader/convert.py'\n")

for i in range(0, 2):
    
    output.write("\nstatic const char " + ARRAY_NAMES[i] + "[] =")

    inp = open(FILE_NAMES[i], "r")

    lines = inp.readlines()

    for l in lines:
        l = l.replace('\n', "")
        output.write("\n")
        output.write('\"' + l + "\\" + "n\"")

    output.write(";\n")
    inp.close()

output.close()


