#ifndef NONEMPTY_SPACE_CORE_INPUT_STATE_H
#define NONEMPTY_SPACE_CORE_INPUT_STATE_H


typedef enum {

    STATE_UP = 0,
    STATE_DOWN = 1,
    STATE_RELEASED = 2,
    STATE_PRESSED = 3,

    STATE_DOWN_OR_PRESSED = STATE_DOWN | STATE_PRESSED

} InputState;


#endif // NONEMPTY_SPACE_CORE_INPUT_STATE_H
