// Generated by a script, see 'shader/convert.py'

static const char VERTEX_SRC[] =
"attribute vec2 vertexPos;\n"
"attribute vec2 vertexUV;\n"
"    \n"
"// uniform mat4 transform;\n"
"    \n"
"uniform vec2 pos;\n"
"uniform vec2 scale;\n"
"    \n"
"varying vec2 uv;\n"
"\n"
"\n"
"void main() {\n"
"    \n"
"    // gl_Position = transform * vec4(vertexPos * scale + pos, 1, 1);\n"
"    gl_Position = vec4(vertexPos * scale + pos, 1, 1);\n"
"    uv = vertexUV;\n"
"}\n";

static const char FRAGMENT_SRC[] =
"uniform sampler2D texSampler;\n"
"    \n"
"varying vec2 uv;\n"
"     \n"
"\n"
"void main() {\n"
"    \n"
"    gl_FragColor = texture2D(texSampler, uv);\n"
"}\n";
